name = "cf-status"
type = "webpack"
workers_dev = true
account_id = "b90d2524a32a3f6782bdc39c3629305b"

kv_namespaces = [
  { binding = "KV", id = "d4b05f679a054aeeb2203549d2264e03" }
]

[triggers]
crons = ["*/2 * * * *"]

