name = "cf-status"
type = "webpack"
workers_dev = true
account_id = "b90d2524a32a3f6782bdc39c3629305b"

kv_namespaces = [
  { binding = "KV", id = "cd16d4566ec0408d84989e51f82488bc" }
]

[triggers]
crons = ["*/2 * * * *"]

