name = "cf-status"
type = "webpack"
workers_dev = true
account_id = "417f5f65df650413531bdc9fc89daf9b"

kv_namespaces = [
  { binding = "KV", id = "213f5605f7014d91afa48e595f0085f6" }
]

[triggers]
crons = ["*/2 * * * *"]

